### ISSUE TITLE
Looking forward to a more complete tutorial

### ISSUE THREAD

**Issue by 0xdd96** [HexHive/Igor#3]
I tried to test my own program following the provided tutorial. However, the are inconsistencies between the program parameters and the description in README. Besides, I also have some questions. Therefore, I am looking forward to a more complete tutorial as soon as possible.

For example, the `trace_pruner.py` run sample given in the [README](https://github.com/HexHive/Igor/blob/main/analyzer/README.md) pointed out that `-a` parameter is a hexadecimal number indicating the address of "the breakpoint in the ASAN enabled environment" here in an ASAN disabled environment.
```
You can prune redundant trace entries(those recorded after the binary's crashing address) by using:

$ python3 trace_pruner.py -i /path/to/trace/files -c /breakpoint/hit/count/dir -o /path/to/result/dir -a $breakpoint_addr
Hint:

The /breakpoint/hit/count/dir is produced by breakpoint_hit_counter.py in an ASAN enabled environment.
The -a parameter is a hexadecimal number indicating the address of "the breakpoint in the ASAN enabled environment" here in an ASAN disabled environment.
```
But the help text of `trace_pruner.py` points out that `-a` points to the argument file path.
```
usage: trace_pruner.py [-h] [-i I] [-c C] [-o O] [-b B] [-a A]

Prune trace files according to a designated address and its breakpoint hit
count

optional arguments:
  -h, --help  show this help message and exit
  -i I        trace file dir
  -c C        breakpoint hit count file
  -o O        result output dir (auto create if not exists)
  -b B        target binary
  -a A        the path of argument file
```

According to my rough understanding, `find_crashing_addr.py` runs PoC to get the crash and analyze the crash point. `breakpoint_hit_counter.py` parses the call stack recovered from the error dump and counts the hit count of each address in the call stack. So, I want to know where the `Debug the binary under test, find the last function the binary calls before crashing, take down its caller's address(usually, the call instruction's address).` mentioned in [README](https://github.com/HexHive/Igor/blob/main/README.md) has been executed. Do I have to do this step manually? Where should I store the results for use in the subsequent processes?

`trace_pruner.py` finds the address of the next call instruction through `self._find_call_ins_addrs(breakpoint_addrs)`, and then writes `trace_file_lines[:stop_idx]` to `output_file`, which does not seem to reduce the trace.

I'm not sure if I have correctly interpreted the tutorial and documents, so I am looking forward to your help to make this process work.

**Comment by mengnanpeter** [comment]
Hi there,

Do you get your problem solved yet? I am looking into this project now, and confusing  about the work flow as you mentioned above.

Hoping someone can make the process clear. Thanks.

**Comment by SonicStark** [comment]
Really, really sorry for the late reply, since we've been troubled by tons of trivial matters in the past few months.

Several possible optimizations are on the way so that those fussy, out-dated and troublesome steps such as counting break-points and ASan on-and-off can be entirely avoided. Plz pay attention to upcoming commits in the next few months.

Best regards.

**Comment by tiedaoxiaotubie** [comment]
@SonicStark contributes quite a lot on Igor, he is now working and maintaining this project. As he said, we don't plan to provide a more detailed documentation since we have solved the above questions by updating our code and providing new features. The next version of Igor would be more convenient and powerful, especially for the tracer and cluster. We will release the code later, and we will appreciate it if more people can contribute for Igor and give PR. If you still insist to use current version, pls ping @SonicStark for help, or ask in discussion of this repo :)
